### ISSUE TITLE
環境使用問題

### ISSUE THREAD

**Issue by ChengYen-Tang** [tu2id4n/HIT_Msp_Agent#7]
我正在幫stable-baselines的 PPO2, A2C, ACKTR, ACER 這4種演算法添加`無效動作遮罩的功能`，需要一些環境驗證我的作法效果如何，剛好看到的專案有使用stable-baselines，想請問是否可以用你的環境驗證。

[https://github.com/NTUT-SE-ST/stable-baselines/tree/neglogp+entropy](https://github.com/NTUT-SE-ST/stable-baselines/tree/neglogp+entropy)

**Comment by tu2id4n** [comment]
可以

发自我的iPhone

**Comment by ChengYen-Tang** [comment]
請問，你將stable-baselines的代碼複製到你的專案有甚麼用途嗎?
還是你對演算法有做修改?

謝謝

**Comment by tu2id4n** [comment]
这个是我提交的比赛用的智能体，你要是看的话，可以看我my pmm那个库

发自我的iPhone

**Comment by tu2id4n** [comment]
没做什么更改，只是改了一下网络结构，然后为适配pommerman环境做了一些更改

发自我的iPhone

**Comment by ChengYen-Tang** [comment]
謝謝，不過我剛剛看了 pommerman 的代碼似乎不適合我的實驗。因為 pommerman 的 reward 蠻稀疏的，遊戲回合結束才會給 reward，過程reward都是0。

我們現在遇到的問題是當屏蔽了 無效動作，導致概率分佈發生改變。所以，不能用原本神經網路出來的概率分佈來計算梯度。密集的給 reward 就會出現下方連結的問題，神經網路爆掉。雖然，我已經改善這個問題，但是沒有適合的環境驗證效果。

[https://github.com/hill-a/stable-baselines/pull/453#issuecomment-553318792](https://github.com/hill-a/stable-baselines/pull/453#issuecomment-553318792)

**Comment by ChengYen-Tang** [comment]
如果你有興趣使用動作遮罩的話可以參考下面兩個檔案，可能可以降低你訓練的step數量

[環境必須在 step 結束時回傳 下一個 step 你期望可以做的 action 。在回傳的 action mask 中， 希望做的 action 是1，不希望做的action 是0](https://github.com/NTUT-SE-ST/stable-baselines/blob/neglogp%2Bentropy/stable_baselines/common/action_mask_env.py)

[https://github.com/NTUT-SE-ST/stable-baselines/blob/neglogp%2Bentropy/tests/test_0action_mask.py](https://github.com/NTUT-SE-ST/stable-baselines/blob/neglogp%2Bentropy/tests/test_0action_mask.py)

**Comment by tu2id4n** [comment]
> 如果你有興趣使用動作遮罩的話可以參考下面兩個檔案，可能可以降低你訓練的step數量
> 
> [環境必須在 step 結束時回傳 下一個 step 你期望可以做的 action 。在回傳的 action mask 中， 希望做的 action 是1，不希望做的action 是0](https://github.com/NTUT-SE-ST/stable-baselines/blob/neglogp%2Bentropy/stable_baselines/common/action_mask_env.py)
> 
> https://github.com/NTUT-SE-ST/stable-baselines/blob/neglogp%2Bentropy/tests/test_0action_mask.py

好的
